<?php

namespace AppBundle\Repository;

/**
 * DeveloppeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeveloppeurRepository extends \Doctrine\ORM\EntityRepository
{
}
