<?php

namespace AppBundle\Repository;

/**
 * FacteurKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacteurKeyRepository extends \Doctrine\ORM\EntityRepository
{
}
