<?php

namespace AppBundle\Repository;

/**
 * NeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NeedRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllOrderBy($col, $tri)
    {
        $qb = $this->createQueryBuilder('n')
                   ->orderBy ('n.'.$col, $tri);

        return $qb->getQuery()->getResult();
    }
}
