doctrine:
  dbal: 
    charset: UTF8
    dbname: "%database_name%"
    driver: pdo_mysql
    host: "%database_host%"
    password: "%database_password%"
    port: "%database_port%"
    user: "%database_user%"
  orm: 
    auto_generate_proxy_classes: "%kernel.debug%"
    auto_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
fos_user: 
  db_driver: orm
  firewall_name: main
  from_email: 
    address: "%mailer_user%"
    sender_name: "%mailer_user%"
  registration: 
    form: 
      type: AppBundle\Form\RegistrationType
  user_class: AppBundle\Entity\User
framework: 
  assets: ~
  csrf_protection: ~
  default_locale: "%locale%"
  form: ~
  fragments: ~
  http_method_override: true
  php_errors: 
    log: true
  router: 
    resource: "%kernel.project_dir%/app/config/routing.yml"
    strict_requirements: ~
  secret: "%secret%"
  session: 
    handler_id: session.handler.native_file
    save_path: "%kernel.project_dir%/var/sessions/%kernel.environment%"
  templating: 
    engines: 
      - twig
  translator: ~
  trusted_hosts: ~
  validation: 
    enable_annotations: true
imports: 
  - 
    resource: parameters.yml
  - 
    resource: security.yml
  - 
    resource: services.yml
parameters: 
  locale: en
swiftmailer: 
  host: "%mailer_host%"
  password: "%mailer_password%"
  spool: 
    type: memory
  transport: "%mailer_transport%"
  username: "%mailer_user%"
twig: 
  debug: "%kernel.debug%"
  form_themes:
    - 'materialize_layout.html.twig'
  strict_variables: "%kernel.debug%"
